name = "9to5-scraper"
main = "dist/index.js"
compatibility_date = "2024-05-01"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "JOB_SCRAPER_DB"
database_id = "11092798-a3d9-44b8-be5f-1835c0027887"

[[kv_namespaces]]
binding = "KV"
id = "5e60b00818e9448b8f965af0fc96d39a"

[[r2_buckets]]
binding = "R2"
bucket_name = "job-scraper"

# Note: Vectorize binding would need to be created through the Cloudflare dashboard
# as it's not available via the current API tools
[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "jobs"

[ai]
binding = "AI"

[vars]
API_AUTH_TOKEN = "test-token"
BROWSER_RENDERING_TOKEN = "browser-token"
SLACK_WEBHOOK_URL = ""

[[triggers.crons]]
cron = "0 * * * *"

[[triggers.crons]]
cron = "0 */3 * * *"
